[build-system]
requires = ["setuptools","setuptools_scm","wheel","requests","dateparser","pycryptodome","mnemonic","hdwallet","bech32", "pyjwt[crypto]", "cryptography", "pycryptodome"]
build-backend = "setuptools.build_meta"